### ISSUE TITLE
USER STORY: A poll to give an opinion about an event 

### ISSUE THREAD

**Issue by mzxz** [mzxz/My-First-Agile-Project#3]
As a **user** I can **select an answer from the poll** so that **I can give my opinion about a running event**

## Acceptance criteria:
* Should have options to vote anonymous or by user name.
* Should be a checkbox next to each option.
* Should have Submit, delete and edit buttons.

## Tasks
- [ ] Create the HTML and CSS for poll's checkbox
- [ ] Create the poll models
- [ ] Test the completed functionality
